on:
  pull_request:

name: lint-shell
permissions:
  contents: write

jobs:
  sh:
    name: sh-verify-syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify script syntax
        run: |
          for file in $(find . -type f -name '*.sh'); do
            echo "::group::${file}"
            echo "Checking ${file}"
            sh -n "${file}"
            echo "::endgroup::"
          done
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
