on:
  pull_request:

name: lint-shell
permissions:
  contents: write

jobs:
  sh:
    name: sh-noexec-verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: |
          find . -type f -name '*.sh' | xargs -n 1 sh -n
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
